# Generated by Django 5.2.8 on 2025-12-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
