# Generated by Django 5.2.8 on 2025-12-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='duracao',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor')], max_length=20),
        ),
    ]
