# Generated by Django 5.2.8 on 2025-12-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_nivel_usuario_xp_total'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='xp_total',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turma'),
        ),
    ]