# Generated by Django 5.2.8 on 2025-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_usuario_disciplina_remove_usuario_nivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='xp_total',
            field=models.IntegerField(default=0, verbose_name='XP Total'),
        ),
    ]
