# Generated by Django 5.2.8 on 2025-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usuario_options_usuario_nivel_usuario_xp_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='melhor_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='streak_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_missao_concluida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acesso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor')], default='ALUNO', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='xp_total',
            field=models.IntegerField(default=0),
        ),
    ]
