# Generated by Django 5.2.8 on 2025-12-07 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usuario_melhor_streak_usuario_streak_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('icone', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('MISSOES', 'Missões'), ('STREAK', 'Sequência'), ('NIVEL', 'Nível'), ('PRECISAO', 'Precisão')], max_length=20)),
                ('condicao_valor', models.IntegerField()),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['ordem', 'condicao_valor'],
            },
        ),
        migrations.CreateModel(
            name='BadgeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('visualizada', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.badge')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_conquistadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge Conquistada',
                'verbose_name_plural': 'Badges Conquistadas',
                'ordering': ['-data_conquista'],
                'unique_together': {('usuario', 'badge')},
            },
        ),
    ]
