# Generated by Django 5.2.8 on 2025-12-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_badge_badgeusuario'),
        ('core', '0006_alter_turma_data_criacao_alter_turma_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='turma',
        ),
        migrations.AddField(
            model_name='usuario',
            name='turmas_aluno',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='core.turma', verbose_name='Turmas do Aluno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor')], max_length=10),
        ),
    ]
