# Generated by Django 5.2.8 on 2025-12-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_usuario_turma_usuario_turmas_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aceitou_termos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_aceite_termos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ip_aceite_termos',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
