# Generated by Django 5.2.8 on 2025-12-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
