# Generated by Django 5.2.8 on 2025-12-05 23:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='missao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
        migrations.AlterModelOptions(
            name='missaoaluno',
            options={'verbose_name': 'Missão do Aluno', 'verbose_name_plural': 'Missões dos Alunos'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AddField(
            model_name='missao',
            name='data_disponivel',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='missao',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BadgeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge Conquistada',
                'verbose_name_plural': 'Badges Conquistadas',
                'unique_together': {('usuario', 'badge')},
            },
        ),
    ]
