# Generated by Django 5.2.8 on 2025-12-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_missao_disciplina_missao_duracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='missao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
        migrations.AlterModelOptions(
            name='missaoaluno',
            options={'verbose_name': 'Missão do Aluno', 'verbose_name_plural': 'Missões dos Alunos'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
    ]
