# Generated by Django 5.2.8 on 2025-12-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=10)),
                ('cor', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='missao',
            name='tipo',
            field=models.CharField(choices=[('QUESTAO', 'Questão com Alternativas'), ('TAREFA', 'Tarefa Livre')], default='TAREFA', max_length=20),
        ),
        migrations.AddField(
            model_name='missaoaluno',
            name='acertou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missaoaluno',
            name='resposta_escolhida',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='missao',
            name='duracao',
            field=models.IntegerField(blank=True, help_text='Duração em minutos', null=True),
        ),
        migrations.AlterField(
            model_name='missao',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina'),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('ordem', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D')], max_length=1)),
                ('correta', models.BooleanField(default=False)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='core.missao')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['ordem'],
                'unique_together': {('missao', 'ordem')},
            },
        ),
    ]
