# Generated by Django 5.2.8 on 2025-12-07 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disciplina_missao_tipo_missaoaluno_acertou_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['-ano_letivo', 'nome'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RemoveField(
            model_name='turma',
            name='codigo',
        ),
        migrations.AddField(
            model_name='turma',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
