# Generated by Django 5.2.8 on 2025-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_turma_data_criacao_alter_turma_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='cor',
            field=models.CharField(default='#667eea', max_length=7),
        ),
    ]
